version: 2.1
orbs:
  node: circleci/node@12.13.0
workflows:
  manual_workflow:
   jobs:
     build: 
        docker:
          - image: cimg/node:12.13.0
        steps:
          - checkout
          - run: npm install