version: 2.1

jobs:
  approval:
    steps:
      - run: |
           echo Approved to deploy preview
    
  build-test-and-approval-deploy:
    docker:
      - image: cimg/node:12.13.0
    steps:
      - checkout 
      - run: |
           echo Preview deployed          

workflows:
  deploy_preview:
    jobs:
      - approval
         type: approval

      - build-test-and-approval-deploy
         requires:
            - approval 