version: 2.1
orbs:
  node: circleci/node@12.13.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:12.13.0
    steps:
      - checkout 
      - run: |
           echo Hello, World!          