version: 2.1

jobs:
  build-test-and-approval-deploy:
    docker:
      - image: cimg/node:12.13.0
    steps:
      - checkout 
      - run: |
           echo Hello, World!          

workflows:
  deploy_preview:
    jobs:
      - build-test-and-approval-deploy
        type: approval 