version: 2.1
orbs:
  node: circleci/node@12.13.0
workflows:
  manual_workflow:
   jobs:
     build: 
        steps:
          - checkout
          - node/install-packages:
            pkg-manager: npm
          - run:
              command: npm run test
              name: Run tests