version: 2.1

jobs:
  # started:
  #   - run: |
  #          echo Workflow stared
  # hold:
  #  - run: |
  #          echo Approved to deploy preview
    
  build-test-and-approval-deploy:
    docker:
      - image: cimg/node:12.13.0
    steps:
      - checkout 
      - run: |
           echo Preview deployed          

workflows:
  deploy_preview:
    jobs:
      - started
        - run: |
           echo Workflow stared
      - hold
          type: approval
          requires:
            - started
          - run: |
           echo Approved to deploy preview  

      - build-test-and-approval-deploy
         requires:
            - hold 