# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Alternative option - authentication via credentials json
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: vars
        name: Set outputs
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"    
        
      - id: deploy
        name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app.yaml'
          promote: false
          version: '${{steps.vars.outputs.sha_short}}'
        
      - name: Preview Url
        run: echo "Hello https://${{steps.vars.outputs.sha_short}}-dot-api-preview-dot-deploy-api-preview.uc.r.appspot.com"
